change: ci: update packages in paralell

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -5,12 +5,39 @@ on:
     - cron: "26 3 * * *" # https://crontab.guru/#26_10_*_*_*
 
 jobs:
+  generate-package-matrix:
+    runs-on: ubuntu-slim
+    outputs:
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v6
+        with:
+          fetch-depth: 0
+      - name: Install nix
+        uses: cachix/install-nix-action@v31
+        with:
+          nix_path: "nixpkgs=channel:nixos-25.11"
+          extra_nix_config: |
+            experimental-features = nix-command flakes
+      - name: Show nixpkgs version
+        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
+      - name: Set package names as JSON output for matrix
+        id: set-matrix
+        run: |
+          set -o -x
+          # excluded from package updates:
+          # mainnet-observer-frontend-placeholder
+          # bitcoind-tracing
+          pkgs=($(nix flake show --json | jq -r '.packages."x86_64-linux" | keys[] ' | grep -v -e mainnet-observer-frontend-placeholder -e bitcoind-tracing | tr '\n' '@'))
+          pkgs_list=$(echo $pkgs | jq -R -s -c 'split("@")[:-1]')
+          echo "matrix={\"package\": $pkgs_list}" >> $GITHUB_OUTPUT
+
   update-flake-packages:
+    needs: generate-package-matrix
     strategy:
       fail-fast: false
-      matrix:
-        nixPath:
-          - nixpkgs=channel:nixos-25.11
+      matrix: ${{ fromJson(needs.generate-package-matrix.outputs.matrix) }}
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
@@ -29,7 +56,7 @@ jobs:
       - name: Install nix
         uses: cachix/install-nix-action@v31
         with:
-          nix_path: "${{ matrix.nixPath }}"
+          nix_path: "nixpkgs=channel:nixos-25.11"
           extra_nix_config: |
             experimental-features = nix-command flakes
 
@@ -45,41 +72,33 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-            set -o xtrace
-            # excluded from package updates:
-            # mainnet-observer-frontend-placeholder
-            # bitcoind-tracing
-            pkgs=($(nix flake show --json | jq -r '.packages."x86_64-linux" | keys[] ' | grep -v -e mainnet-observer-frontend-placeholder -e bitcoind-tracing))
-            for i in "${pkgs[@]}"
-            do
-              git checkout master
-              echo "trying to update package: '$i'"
-              # Don't do the updates while on master, otherwise we pollute it with updates of other packages
-              BRANCH="auto-update-$i"
-              git branch -D $BRANCH || true
-              git checkout -b $BRANCH
-              CURRENT_HEAD=$(git log -1 --format=%H)
-              # HACK: "... || true" to avoid failing when no update is avaliable
-              nix-shell -p nix-update --run "nix-update --flake --commit --build --version=branch $i || true"
-              NEW_HEAD=$(git log -1 --format=%H)
+            set -o -x
+            git checkout master
+            echo "trying to update package: '${{ matrix.package }}'"
+            # Don't do the updates while on master, otherwise we pollute it with updates of other packages
+            BRANCH="auto-update-${{ matrix.package }}"
+            git branch -D $BRANCH || true
+            git checkout -b $BRANCH
+            CURRENT_HEAD=$(git log -1 --format=%H)
+            # HACK: "... || true" to avoid failing when no update is avaliable
+            nix-shell -p nix-update --run "nix-update --flake --commit --build --version=branch ${{ matrix.package }} || true"
+            NEW_HEAD=$(git log -1 --format=%H)
 
-              if [ "$CURRENT_HEAD" = "$NEW_HEAD" ]; then
-                echo "Package $i wasn't updated - doing nothing."
-                git restore pkgs/
-                continue
-              else
-                git log -1
-              fi
+            if [ "$CURRENT_HEAD" = "$NEW_HEAD" ]; then
+              echo "Package ${{ matrix.package }} wasn't updated - doing nothing."
+              git restore pkgs/
+              exit 0
+            else
+              git log -1
+            fi
 
-              git push --set-upstream origin $BRANCH --force
+            git push --set-upstream origin $BRANCH --force
 
-              # Only open a PR if the branch is not attached to an existing one
-              PR=$(gh pr list --head $BRANCH --json number -q '.[0].number')
-              if [ -z $PR ]; then
-                PR_TITLE="$i: $(date -Idate) automated package update"
-                gh pr create --head $BRANCH --title="$PR_TITLE" --body="Auto updating package '$i'. See commit(s) for details." --reviewer 0xb10c
-              else
-                echo "Pull request already exists, won't create a new one."
-              fi
-
-            done
+            # Only open a PR if the branch is not attached to an existing one
+            PR=$(gh pr list --head $BRANCH --json number -q '.[0].number')
+            if [ -z $PR ]; then
+              PR_TITLE="${{ matrix.package }}: $(date -Idate) automated package update"
+              gh pr create --head $BRANCH --title="$PR_TITLE" --body="Auto updating package '${{ matrix.package }}'. See commit(s) for details." --reviewer 0xb10c
+            else
+              echo "Pull request already exists, won't create a new one."
+            fi
